FROM node:18-slim

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Installer les dépendances nécessaires
RUN apt-get update && \
    apt-get install -y build-essential python3 && \
    rm -rf /var/lib/apt/lists/*

# Copier les fichiers essentiels pour l'installation
COPY package.json ./
COPY .env ./

# Installer les dépendances
RUN npm install --legacy-peer-deps

# Copier le reste du code
COPY . .

# Exposer le port du service
EXPOSE 3000

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev"] 